### ISSUE TITLE
Getting issue with fragments

### ISSUE THREAD

**Issue by pratikbutani** [MohamedWessam/no-internet-layout#2]
What If I want to use this layout in Fragments? 

I have tried with this way:

`new NoInternetLayout.Builder(getActivity(), R.layout.fragment_privacy_policy);`

- Its displaying full screen internet view
- If I press back button, its finishing activity.

**Comment by MohamedWessam** [comment]
thank you for submitting this issue.
Actually it works only with Activity till now. this library started too simple, and I am trying to figure out a good way to work with fragments

**Comment by pratikbutani** [comment]
Nice. Keep it up. Thank you for your library.
