### ISSUE TITLE
Failed to resolve issue with gradle

### ISSUE THREAD

**Issue by amanasci** [MohamedWessam/no-internet-layout#5]
Experiencing failed to resolve issue when trying to add it in gradle file.

> ERROR: Failed to resolve: com.github.MohamedWessam:no-internet-layout:0.1.1
Show in Project Structure dialog
Affected Modules: app

**Comment by MohamedWessam** [comment]
Have you added this code to your **allprojects** script in your top level **build.gradle**?

`

    allprojects {
        repositories {
            google()
            jcenter()
            maven { url "https://jitpack.io" }
        }
    }
`

**Comment by amanasci** [comment]
Yes, I already did that. 
I don't know what's causing this issue. I am using more libraries from jitpack repo, they are working fine.

**Comment by AhmedSenosy** [comment]
Same issue with me
